branch-defaults:
  beanstark:
    environment: hellowerldapp
  pickles:
    environment: hellowerldapp
deploy:
  artifact: target/aznserverjsonparsticator-0.0.1.jar
environment-defaults:
  hellowerldapp:
    branch: null
    repository: null
global:
  application_name: HelloWerldApp
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Java 8
  default_region: us-west-2
  profile: eb-cli
  sc: git
